-- ============================================================
-- SilkFutures Pathways — V32 Migration: Check-In Questionnaires & Their Voice
-- Run this in Supabase SQL Editor AFTER v31 migration
-- ============================================================

-- 1. Check-in questionnaires table
-- Stores AI-generated questionnaires and the young person's responses.
-- Each row is one questionnaire instance (5-6 questions + answers).
CREATE TABLE IF NOT EXISTS checkin_questionnaires (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  young_person_id UUID NOT NULL REFERENCES young_people(id) ON DELETE CASCADE,
  mentor_id UUID NOT NULL REFERENCES mentors(id),
  stage TEXT NOT NULL,
  questions JSONB NOT NULL DEFAULT '[]',
  responses JSONB DEFAULT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed')),
  created_at TIMESTAMPTZ DEFAULT now(),
  completed_at TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_checkin_yp ON checkin_questionnaires(young_person_id);
CREATE INDEX IF NOT EXISTS idx_checkin_status ON checkin_questionnaires(status);

-- 2. RLS — open for now (same as other tables, PIN auth not Supabase Auth)
ALTER TABLE checkin_questionnaires ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to checkin_questionnaires"
  ON checkin_questionnaires FOR ALL USING (true) WITH CHECK (true);

-- 3. Ensure yp_feedback cascade works for hard deletes
-- (Already has ON DELETE CASCADE from setup, but verify)
-- No change needed — just documenting that soft-deleted sessions
-- need to be filtered client-side in the "Their Voice" section.

-- Done. The check-in questionnaire system is ready.
-- Questions are generated by AI via /api/checkin-generate
-- Responses are saved back to this table when the YP completes them.
