export const maxDuration = 60;
import { NextResponse } from "next/server";

function generateICS({ title, date, startTime, durationMins, location, description, uid }) {
  const [year, month, day] = date.split("-").map(Number);
  const [hour, min] = (startTime || "14:00").split(":").map(Number);
  const pad = (n) => String(n).padStart(2, "0");
  const dtStart = `${year}${pad(month)}${pad(day)}T${pad(hour)}${pad(min)}00`;
  const endDate = new Date(year, month - 1, day, hour, min + durationMins);
  const dtEnd = `${endDate.getFullYear()}${pad(endDate.getMonth() + 1)}${pad(endDate.getDate())}T${pad(endDate.getHours())}${pad(endDate.getMinutes())}00`;
  const now = new Date();
  const dtStamp = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}T${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}Z`;

  return [
    "BEGIN:VEVENT",
    `UID:${uid}`,
    `DTSTAMP:${dtStamp}`,
    `DTSTART;TZID=Europe/London:${dtStart}`,
    `DTEND;TZID=Europe/London:${dtEnd}`,
    `SUMMARY:${title}`,
    `LOCATION:${location || ""}`,
    `DESCRIPTION:${(description || "").replace(/\n/g, "\\n")}`,
    "STATUS:CONFIRMED",
    "BEGIN:VALARM",
    "TRIGGER:-PT30M",
    "ACTION:DISPLAY",
    "DESCRIPTION:Session reminder",
    "END:VALARM",
    "END:VEVENT",
  ].join("\r\n");
}

function buildICSFile(events) {
  const header = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//SilkFutures//Pathways//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:SilkFutures Pathways",
  ].join("\r\n");
  const footer = "END:VCALENDAR";
  return header + "\r\n" + events.join("\r\n") + "\r\n" + footer;
}

export async function POST(req) {
  try {
    const body = await req.json();
    const { type } = body;

    const resendKey = process.env.RESEND_API_KEY;

    // ── IMPACT REPORT EMAIL ──
    if (type === "impact-report-email") {
      const { mentorEmail, mentorName, report, projectName, dateRange } = body;
      if (!resendKey || !mentorEmail) return NextResponse.json({ error: "Missing email config", sent: false });

      const sections = [
        report.executiveSummary && `<h3 style="color:#2563EB;font-size:14px;margin:20px 0 8px;">Executive Summary</h3><p style="font-size:13px;line-height:1.8;color:#333;white-space:pre-line;">${report.executiveSummary}</p>`,
        report.keyMetrics && `<h3 style="color:#2563EB;font-size:14px;margin:20px 0 8px;">Key Metrics</h3><p style="font-size:13px;line-height:1.8;color:#333;white-space:pre-line;">${report.keyMetrics}</p>`,
        (report.outcomesEvidence || report.outcomes) && `<h3 style="color:#059669;font-size:14px;margin:20px 0 8px;">Outcomes Evidence</h3><p style="font-size:13px;line-height:1.8;color:#333;white-space:pre-line;">${report.outcomesEvidence || report.outcomes}</p>`,
        report.caseStudies && `<h3 style="color:#7C3AED;font-size:14px;margin:20px 0 8px;">Case Studies</h3><p style="font-size:13px;line-height:1.8;color:#333;white-space:pre-line;">${report.caseStudies}</p>`,
        report.challenges && `<h3 style="color:#666;font-size:14px;margin:20px 0 8px;">Challenges</h3><p style="font-size:13px;line-height:1.8;color:#555;white-space:pre-line;">${report.challenges}</p>`,
        report.recommendations && `<h3 style="color:#2563EB;font-size:14px;margin:20px 0 8px;">Recommendations</h3><p style="font-size:13px;line-height:1.8;color:#333;white-space:pre-line;">${report.recommendations}</p>`,
      ].filter(Boolean).join("");

      const emailHtml = `
        <div style="font-family:'Helvetica Neue',Arial,sans-serif;max-width:700px;margin:0 auto;padding:24px;">
          <div style="border-bottom:2px solid #1A1A1A;padding-bottom:12px;margin-bottom:20px;">
            <strong style="font-size:16px;">SilkFutures Pathways</strong>
          </div>
          <h2 style="font-size:20px;margin:0 0 4px;">${report.title || "Impact Report"}</h2>
          <p style="color:#888;font-size:13px;margin:0 0 4px;">${report.subtitle || `${projectName} — ${dateRange}`}</p>
          <p style="color:#bbb;font-size:11px;margin:0 0 20px;">Generated by ${mentorName} on ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}</p>
          ${sections}
          <p style="font-size:11px;color:#bbb;margin-top:32px;border-top:1px solid #eee;padding-top:12px;">Generated by SilkFutures Pathways</p>
        </div>
      `;

      const res = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${resendKey}` },
        body: JSON.stringify({
          from: "SilkFutures Pathways <pathways@silkfutures.com>",
          to: [mentorEmail],
          subject: `📊 Impact Report: ${projectName} — ${dateRange}`,
          html: emailHtml,
        }),
      });
      const data = await res.json();
      return NextResponse.json({ sent: res.ok, details: data });
    }

    // ── SESSION NOTIFY EMAIL (existing) ──
    const { mentorName, mentorEmail, sessions } = body;

    if (!resendKey || !mentorEmail) {
      return NextResponse.json({ error: "Missing email config or mentor email", sent: false });
    }

    if (!sessions || sessions.length === 0) {
      return NextResponse.json({ error: "No sessions to notify about", sent: false });
    }

    // Build ICS events for all sessions
    const icsEvents = sessions.map((s, i) => {
      const len = (s.session_length || "1 Hour").toLowerCase();
      const num = parseFloat(len) || 1;
      const durationMins = len.includes("min") ? num : num * 60;
      const uid = `pathways-${s.date}-${(s.time || s.start_time || "1400").replace(":", "")}-${i}-${Date.now()}@silkfutures.com`;

      return generateICS({
        title: `Pathways: ${s.young_person_name}`,
        date: s.date,
        startTime: s.time || s.start_time || "14:00",
        durationMins,
        location: s.location || "SilkFutures",
        description: `Session with ${s.young_person_name}\\nLocation: ${s.location || "SilkFutures"}\\nDuration: ${s.session_length}`,
        uid,
      });
    });

    const icsContent = buildICSFile(icsEvents);
    const icsBase64 = Buffer.from(icsContent).toString("base64");

    // Build session rows for HTML email
    const sessionRows = sessions.map(s => {
      const d = new Date(s.date + "T12:00");
      const dayLabel = d.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" });
      return `
        <tr>
          <td style="padding: 8px 12px; border-bottom: 1px solid #eee; font-weight: 600;">${s.young_person_name}</td>
          <td style="padding: 8px 12px; border-bottom: 1px solid #eee;">${dayLabel}</td>
          <td style="padding: 8px 12px; border-bottom: 1px solid #eee;">${s.time || s.start_time || "TBC"}</td>
          <td style="padding: 8px 12px; border-bottom: 1px solid #eee;">${s.location || "SilkFutures"}</td>
        </tr>
      `;
    }).join("");

    const emailHtml = `
      <div style="font-family: 'Helvetica Neue', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
        <div style="border-bottom: 2px solid #1A1A1A; padding-bottom: 12px; margin-bottom: 20px;">
          <strong style="font-size: 16px;">SilkFutures Pathways</strong>
        </div>
        <h2 style="font-size: 20px; margin: 0 0 6px;">Your Sessions This Week</h2>
        <p style="color: #666; font-size: 14px; margin: 0 0 20px;">Hi ${mentorName}, here's what's coming up.</p>
        <table style="width: 100%; font-size: 13px; border-collapse: collapse;">
          <thead>
            <tr style="background: #f7f5f2;">
              <th style="padding: 8px 12px; text-align: left; font-size: 10px; text-transform: uppercase; color: #888; letter-spacing: 0.05em;">Young Person</th>
              <th style="padding: 8px 12px; text-align: left; font-size: 10px; text-transform: uppercase; color: #888; letter-spacing: 0.05em;">Date</th>
              <th style="padding: 8px 12px; text-align: left; font-size: 10px; text-transform: uppercase; color: #888; letter-spacing: 0.05em;">Time</th>
              <th style="padding: 8px 12px; text-align: left; font-size: 10px; text-transform: uppercase; color: #888; letter-spacing: 0.05em;">Location</th>
            </tr>
          </thead>
          <tbody>
            ${sessionRows}
          </tbody>
        </table>
        <p style="font-size: 13px; color: #888; margin-top: 24px;">Open the attached .ics file to add these sessions to your calendar.</p>
        <p style="font-size: 11px; color: #bbb; margin-top: 16px;">Sent from SilkFutures Pathways</p>
      </div>
    `;

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${resendKey}` },
      body: JSON.stringify({
        from: "SilkFutures Pathways <pathways@silkfutures.com>",
        to: [mentorEmail],
        subject: `📅 Your Pathways Sessions This Week — ${sessions.length} session${sessions.length !== 1 ? "s" : ""}`,
        html: emailHtml,
        attachments: [
          {
            filename: "pathways-sessions.ics",
            content: icsBase64,
            content_type: "application/ics",
          },
        ],
      }),
    });

    const data = await res.json();
    if (!res.ok) {
      return NextResponse.json({ error: "Email send failed", details: data, sent: false });
    }

    return NextResponse.json({ sent: true });
  } catch (err) {
    return NextResponse.json({ error: err.message, sent: false }, { status: 500 });
  }
}
